# https://taskfile.dev

version: '3'

vars:
  PLUGIN_NAME: mrmarble/opsd
  PLUGIN_VERSION:
    sh: git describe --tags --dirty --always --abbrev=12 || echo 'dev'

tasks:
  default:
    silent: true
    cmds:
      - task: clean
      - task: rootfs
      - task: disable
      - task: create

  clean:
    silent: true
    desc: Remove temporal folders
    cmds:
      - rm -rf ./plugin

  rootfs:
    silent: true
    desc: Build the rootfs needed for the plugin
    cmds:
      - docker build --build-arg VERSION={{.PLUGIN_VERSION}} -t {{.PLUGIN_NAME}}:rootfs .
      - mkdir -p ./plugin/rootfs
      - docker create --name opsd-rootfs {{.PLUGIN_NAME}}:rootfs
      - docker export opsd-rootfs | tar -x -C ./plugin/rootfs
      - cp config.json ./plugin/
      - docker rm -vf opsd-rootfs

  create:
    desc: Create Docker Plugin
    cmds:
      - docker plugin rm -f {{.PLUGIN_NAME}}:{{.PLUGIN_VERSION}} || true
      - docker plugin create {{.PLUGIN_NAME}}:{{.PLUGIN_VERSION}} ./plugin

  disable:
    desc: Disable local plugin
    cmds:
      - docker plugin disable {{.PLUGIN_NAME}}:{{.PLUGIN_VERSION}} || true

  enable:
    desc: Enable local plugin
    cmds:
      - docker plugin enable {{.PLUGIN_NAME}}:{{.PLUGIN_VERSION}}
  lint:
    desc: Lint the code
    cmds:
      - go vet ./...
      - go tool staticcheck ./...
      - go tool revive ./...
